services:
  postgres:
    container_name: boticarium_db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: boticarium_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia: Guarda los datos aunque apagues el contenedor
    restart: always                   # Si falla, intenta reiniciarse solo

volumes:
  postgres_data: